#!/usr/bin/python3

import random
import sys

try:
    n = int(sys.argv[1])
    s = ""
    for i in range(n):
        s += chr(random.randint(ord('!'), ord('~')))
    print(s)
except:
    print("Ошибка. Вы не ввели длину пароля. Попробуйте ещё раз.")
